replicaCount: 1

image:
  repository: 831192476748.dkr.ecr.ap-southeast-1.amazonaws.com/llm-service
  tag: latest
  pullPolicy: IfNotPresent

nodeSelector: {}
tolerations: []

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 4Gi
